"use client";
import { useEffect, useState } from "react";
import { DailyRecapStudio } from "./DailyRecapStudio";
import { ActivityStudio } from "./ActivityStudio";
import { ParticipantManagement } from "./ParticipantManagement";
import { AnnouncementStudio } from "./AnnouncementStudio";
import { ResourceStudio } from "./ResourceStudio";
import { FeedbackStudio } from "./FeedbackStudio";
type Overview={counts:{registrations:number;feedback:number;resources:number;reservations:number};registrations:{id:number;fullName:string;organization:string;participationType:string}[];feedback:{id:number;category:string;rating:number;message:string}[];notifications:{id:number;kind:string;title:string;detail:string;contactEmail:string;emailStatus:string;createdAt:string}[];activityReservations:{id:number;userEmail:string;activityId:string;createdAt:string}[]};
export function AdminStudio(){const[data,setData]=useState<Overview|null>(null);const load=()=>fetch("/api/admin/overview").then(r=>r.json()).then(setData);useEffect(()=>{void load()},[]);
return <><div className="form-actions" style={{marginBottom:18}}><a className="button button-secondary" href="/api/admin/export?type=registrations">Export registrations</a><a className="button button-secondary" href="/api/admin/export?type=reservations">Export reservations</a><a className="button button-secondary" href="/api/admin/export?type=feedback">Export feedback</a></div>
  <div className="admin-metrics admin-metrics-four"><div className="metric"><strong>{data?.counts.registrations??"—"}</strong><span>registrations</span></div><div className="metric"><strong>{data?.counts.reservations??"—"}</strong><span>experience reservations</span></div><div className="metric"><strong>{data?.counts.feedback??"—"}</strong><span>feedback entries</span></div><div className="metric"><strong>{data?.counts.resources??"—"}</strong><span>published resources</span></div></div>
  <ParticipantManagement/>
  <div className="admin-grid"><ResourceStudio onChanged={load}/><AnnouncementStudio/></div>
  <div className="admin-grid" style={{marginTop:18}}><section className="dashboard-card"><h2>Latest registrations</h2><div className="admin-list">{data?.registrations?.length?data.registrations.map(r=><div className="admin-list-item" key={r.id}><span><strong>{r.fullName}</strong><br/>{r.organization}</span><span>{r.participationType}</span></div>):<p className="form-status">No registrations yet.</p>}</div></section><section className="dashboard-card"><h2>Latest feedback</h2><div className="admin-list">{data?.feedback?.length?data.feedback.map(f=><div className="admin-list-item" key={f.id}><span><strong>{f.category} · {f.rating}/5</strong><br/>{f.message.slice(0,95)}</span></div>):<p className="form-status">No feedback yet.</p>}</div></section></div>
  <section className="dashboard-card" style={{marginTop:18}}><div className="dashboard-head" style={{marginBottom:12}}><div><span className="tag">PRIVATE ADMIN ACTIVITY</span><h2>Registration & request inbox</h2></div><span className="status-pill">Admin only</span></div><div className="admin-list">{data?.notifications?.length?data.notifications.map(item=><div className="admin-list-item" key={item.id}><span><strong>{item.title}</strong><br/>{item.detail.slice(0,150)}{item.contactEmail&&<><br/><small>{item.contactEmail}</small></>}</span><span><small>{item.createdAt.slice(0,16).replace("T"," ")}</small><br/><small>{item.emailStatus==="sent"?"Email sent":"Saved in admin inbox"}</small></span></div>):<p className="form-status">New registrations and requests will appear here automatically.</p>}</div></section>
  <section className="dashboard-card" style={{marginTop:18}}><div className="dashboard-head" style={{marginBottom:12}}><div><span className="tag">EXPERIENCE PLANNING</span><h2>Dinners & excursion reservations</h2></div><span className="status-pill">Admin only</span></div><div className="admin-list">{data?.activityReservations?.length?data.activityReservations.map(item=><div className="admin-list-item" key={item.id}><span><strong>{item.activityId.split("-").map(word=>word[0].toUpperCase()+word.slice(1)).join(" ")}</strong><br/><small>{item.userEmail}</small></span><span><small>{item.createdAt.slice(0,16).replace("T"," ")}</small></span></div>):<p className="form-status">Participant reservations will appear here automatically.</p>}</div></section>
  <div style={{marginTop:18}}><FeedbackStudio/></div>
  <ActivityStudio/>
  <div style={{marginTop:18}}><DailyRecapStudio/></div>
</>}
