"use client";
import { FormEvent, useEffect, useState } from "react";
import { DailyRecapStudio } from "./DailyRecapStudio";
import { ActivityStudio } from "./ActivityStudio";
import { ParticipantManagement } from "./ParticipantManagement";
type Overview={counts:{registrations:number;feedback:number;resources:number;reservations:number};registrations:{id:number;fullName:string;organization:string;participationType:string}[];feedback:{id:number;category:string;rating:number;message:string}[];notifications:{id:number;kind:string;title:string;detail:string;contactEmail:string;emailStatus:string;createdAt:string}[];activityReservations:{id:number;userEmail:string;activityId:string;createdAt:string}[]};
export function AdminStudio(){const[data,setData]=useState<Overview|null>(null);const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);const load=()=>fetch("/api/admin/overview").then(r=>r.json()).then(setData);useEffect(()=>{void load()},[]);
async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setStatus("");const form=e.currentTarget;try{const res=await fetch("/api/resources",{method:"POST",body:new FormData(form)});const d=await res.json() as {error?:string};if(!res.ok)throw new Error(d.error||"Upload failed");setStatus("Resource published successfully.");form.reset();await load()}catch(err){setStatus(err instanceof Error?err.message:"Upload failed")}finally{setBusy(false)}}
async function announce(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget;try{const res=await fetch("/api/admin/announcements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const d=await res.json() as {error?:string};if(!res.ok)throw new Error(d.error||"Could not publish");setStatus("Announcement published.");form.reset()}catch(err){setStatus(err instanceof Error?err.message:"Could not publish")}finally{setBusy(false)}}
return <><div className="form-actions" style={{marginBottom:18}}><a className="button button-secondary" href="/api/admin/export?type=registrations">Export registrations</a><a className="button button-secondary" href="/api/admin/export?type=reservations">Export reservations</a><a className="button button-secondary" href="/api/admin/export?type=feedback">Export feedback</a></div>
  <div className="admin-metrics admin-metrics-four"><div className="metric"><strong>{data?.counts.registrations??"—"}</strong><span>registrations</span></div><div className="metric"><strong>{data?.counts.reservations??"—"}</strong><span>experience reservations</span></div><div className="metric"><strong>{data?.counts.feedback??"—"}</strong><span>feedback entries</span></div><div className="metric"><strong>{data?.counts.resources??"—"}</strong><span>published resources</span></div></div>
  <ParticipantManagement/>
  <div className="admin-grid"><section className="dashboard-card"><h2>Publish a resource</h2><form onSubmit={upload} className="form-grid"><div className="field full"><label>Title *</label><input name="title" required/></div><div className="field"><label>Category *</label><select name="category"><option>Programme</option><option>Registration</option><option>Travel</option><option>Technical papers</option><option>Speaker presentations</option><option>Hotels</option><option>Sponsor material</option><option>Media</option><option>Certificates</option></select></div><div className="field"><label>Visibility</label><select name="visibility"><option value="public">Public</option><option value="participant">Signed-in participants</option></select></div><div className="field full"><label>Description</label><textarea name="description"/></div><div className="field full upload-zone"><label>Choose file (max 20 MB) *</label><input name="file" type="file" required/></div><div className="form-actions field full"><button className="button" disabled={busy}>{busy?"Publishing…":"Upload & publish"}</button></div></form></section>
  <section className="dashboard-card"><h2>Post an announcement</h2><form onSubmit={announce} className="form-grid"><div className="field full"><label>Headline *</label><input name="title" required/></div><div className="field full"><label>Update *</label><textarea name="body" required/></div><div className="field"><label>Type</label><select name="level"><option value="update">Event update</option><option value="important">Important</option><option value="deadline">Deadline</option></select></div><div className="form-actions field full"><button className="button button-dark" disabled={busy}>Publish update</button></div></form>{status&&<p className="form-status">{status}</p>}</section></div>
  <div className="admin-grid" style={{marginTop:18}}><section className="dashboard-card"><h2>Latest registrations</h2><div className="admin-list">{data?.registrations?.length?data.registrations.map(r=><div className="admin-list-item" key={r.id}><span><strong>{r.fullName}</strong><br/>{r.organization}</span><span>{r.participationType}</span></div>):<p className="form-status">No registrations yet.</p>}</div></section><section className="dashboard-card"><h2>Latest feedback</h2><div className="admin-list">{data?.feedback?.length?data.feedback.map(f=><div className="admin-list-item" key={f.id}><span><strong>{f.category} · {f.rating}/5</strong><br/>{f.message.slice(0,95)}</span></div>):<p className="form-status">No feedback yet.</p>}</div></section></div>
  <section className="dashboard-card" style={{marginTop:18}}><div className="dashboard-head" style={{marginBottom:12}}><div><span className="tag">PRIVATE ADMIN ACTIVITY</span><h2>Registration & request inbox</h2></div><span className="status-pill">Admin only</span></div><div className="admin-list">{data?.notifications?.length?data.notifications.map(item=><div className="admin-list-item" key={item.id}><span><strong>{item.title}</strong><br/>{item.detail.slice(0,150)}{item.contactEmail&&<><br/><small>{item.contactEmail}</small></>}</span><span><small>{item.createdAt.slice(0,16).replace("T"," ")}</small><br/><small>{item.emailStatus==="sent"?"Email sent":"Saved in admin inbox"}</small></span></div>):<p className="form-status">New registrations and requests will appear here automatically.</p>}</div></section>
  <section className="dashboard-card" style={{marginTop:18}}><div className="dashboard-head" style={{marginBottom:12}}><div><span className="tag">EXPERIENCE PLANNING</span><h2>Dinners & excursion reservations</h2></div><span className="status-pill">Admin only</span></div><div className="admin-list">{data?.activityReservations?.length?data.activityReservations.map(item=><div className="admin-list-item" key={item.id}><span><strong>{item.activityId.split("-").map(word=>word[0].toUpperCase()+word.slice(1)).join(" ")}</strong><br/><small>{item.userEmail}</small></span><span><small>{item.createdAt.slice(0,16).replace("T"," ")}</small></span></div>):<p className="form-status">Participant reservations will appear here automatically.</p>}</div></section>
  <ActivityStudio/>
  <div style={{marginTop:18}}><DailyRecapStudio/></div>
</>}
