"use client";
import { useEffect, useMemo, useState } from "react";
type Resource={id:number;title:string;description:string;category:string;fileName:string;sizeBytes:number;createdAt:string};
const categories=["All","Programme","Registration","Travel","Technical","Media"];
export function ResourceLibrary(){const[resources,setResources]=useState<Resource[]>([]);const[loading,setLoading]=useState(true);const[category,setCategory]=useState("All");const[query,setQuery]=useState("");useEffect(()=>{fetch("/api/resources").then(r=>r.json()).then((d:{resources?:Resource[]})=>setResources(d.resources||[])).finally(()=>setLoading(false))},[]);const filtered=useMemo(()=>resources.filter(r=>(category==="All"||r.category===category)&&(`${r.title} ${r.description}`.toLowerCase().includes(query.toLowerCase()))),[resources,category,query]);return <>
  <div className="resource-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search documents and forms…" aria-label="Search resources"/><div className="filter-row">{categories.map(c=><button className={`filter-chip ${category===c?"active":""}`} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div></div>
  <div className="resource-grid">{loading?<div className="empty-state">Loading the library…</div>:filtered.length?filtered.map(r=><article className="resource-card" key={r.id}><div className="file-icon">↓</div><span className="tag">{r.category}</span><h3>{r.title}</h3><p>{r.description||"Official event resource"}</p><div className="resource-meta"><span>{formatBytes(r.sizeBytes)}</span><a className="download-link" href={`/api/resources/${r.id}/download`}>Download ↓</a></div></article>):<div className="empty-state"><strong>No matching files yet.</strong><p>The organizer can publish programmes, forms, travel notes and presentations from the studio.</p></div>}</div>
  </>}
function formatBytes(bytes:number){if(!bytes)return"File";if(bytes<1024*1024)return`${Math.ceil(bytes/1024)} KB`;return`${(bytes/1024/1024).toFixed(1)} MB`}
