export type EventActivity={id:string;day:number;date:string;time:string;endTime:string;title:string;type:"Dinner"|"Excursion"|"Reception"|"Networking";location:string;description:string;capacity:number};
export const EVENT_ACTIVITIES:EventActivity[]=[
  {id:"welcome-reception",day:1,date:"2027-04-19",time:"18:30",endTime:"20:00",title:"Welcome Reception",type:"Reception",location:"Venue to be confirmed",description:"Placeholder official welcome reception. Final format, venue, time and capacity require organizer approval.",capacity:150},
  {id:"networking-dinner",day:2,date:"2027-04-20",time:"19:30",endTime:"22:00",title:"Official Networking Dinner",type:"Dinner",location:"Venue to be confirmed",description:"Placeholder networking dinner for participants, speakers and partners. Details remain unconfirmed.",capacity:180},
  {id:"technical-excursion",day:3,date:"2027-04-21",time:"14:30",endTime:"18:00",title:"Technical Excursion",type:"Excursion",location:"Departure point to be confirmed",description:"Placeholder post-symposium technical excursion. Scope, transport, safety requirements and capacity are pending.",capacity:40},
  {id:"abidjan-cultural-experience",day:3,date:"2027-04-21",time:"15:00",endTime:"18:30",title:"Abidjan Cultural Experience",type:"Excursion",location:"Departure point to be confirmed",description:"Placeholder optional cultural activity. Route, operator, price and capacity are pending organizer approval.",capacity:50},
];
export const CORE_AGENDA:Record<number,{time:string;title:string;location:string;kind:string}[]>={
  1:[{time:"08:00",title:"Registration & welcome coffee",location:"Event venue · to be confirmed",kind:"Arrival"},{time:"09:00",title:"Opening perspectives",location:"Plenary hall · draft",kind:"Plenary"},{time:"10:30",title:"Regional architecture",location:"Technical room · draft",kind:"Technical"},{time:"13:30",title:"Petroleum systems & charge",location:"Technical room · draft",kind:"Technical"}],
  2:[{time:"09:00",title:"Discoveries, fields & lessons learned",location:"Plenary hall · draft",kind:"Technical"},{time:"11:00",title:"Emerging plays & frontier potential",location:"Technical room · draft",kind:"Technical"},{time:"14:00",title:"Case studies & post-well analysis",location:"Technical room · draft",kind:"Case studies"}],
  3:[{time:"09:00",title:"Data & integrated workflows",location:"Plenary hall · draft",kind:"Technical"},{time:"11:00",title:"Development, production & gas",location:"Technical room · draft",kind:"Strategy"},{time:"13:30",title:"Future of the Transform Margin",location:"Plenary hall · draft",kind:"Closing panel"}],
};
export function programmeSessionId(day:number,item:{time:string;title:string}){return `day-${day}-${item.time.replace(":","")}-${item.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}`}
export const PROGRAMME_SESSIONS=Object.entries(CORE_AGENDA).flatMap(([day,items])=>items.map(item=>({...item,day:Number(day),id:programmeSessionId(Number(day),item)})));
