import {eq} from "drizzle-orm";import {getDb} from "@/db";import {activityReservations} from "@/db/schema";import {getEventUser} from "@/lib/event-auth";import {EVENT_ACTIVITIES} from "@/lib/event-program";
const knowledge=[
  {terms:["where","location","venue","place","abidjan"],answer:"The symposium will take place in Abidjan, Côte d’Ivoire, from 19–21 April 2027. The specific venue and recommended hotels will be announced by the organizers.",links:[{label:"Venue information",href:"/travel#venue"}]},
  {terms:["when","date","time","april"],answer:"The event is scheduled for 19–21 April 2027. Detailed session times are still awaiting organizer approval.",links:[{label:"Programme preview",href:"/programme"}]},
  {terms:["organizer","organisation","organization","aapg","eage"],answer:"The symposium is organized by AAPG and EAGE, with support from a regional technical committee.",links:[{label:"Technical committee",href:"/committee"}]},
  {terms:["theme","technical","geology","petroleum","exploration","jubilee","baleine"],answer:"The confirmed outline covers regional transform-margin architecture; petroleum systems and reservoir fairways; discoveries and lessons learned; frontier plays; integrated data workflows; and development, gas and future strategy.",links:[{label:"Technical themes",href:"/technical-themes"}]},
  {terms:["register","registration","sign up","participant"],answer:"Choose Register for Event, verify your email with the six-digit code, complete the event form and you will enter your private participant hub automatically.",links:[{label:"Register for Event",href:"/register"}]},
  {terms:["travel","visa","hotel","accommodation","airport","flight","transportation"],answer:"Official travel, visa, airport transfer and accommodation guidance is not yet confirmed. All approved information will be maintained under Register & Travel; please do not rely on unverified information for non-refundable arrangements.",links:[{label:"Register & Travel",href:"/travel"}]},
  {terms:["speaker","presenter"],answer:"Confirmed speakers and biographies have not yet been announced. They will appear only after organizer approval.",links:[{label:"Speakers",href:"/speakers"}]},
  {terms:["sponsor","sponsorship","exhibit","exhibitor","floor plan","brand builder"],answer:"Sponsorship packages, exhibit space, exhibitor registration and the floor plan are awaiting organizer approval. Approved commercial information will be published only in Exhibit & Sponsor.",links:[{label:"Exhibit & Sponsor",href:"/sponsors"}]},
  {terms:["download","resource","paper","programme pdf"],answer:"Public and participant-only materials are organized in the resource library. New files will appear as the organizers publish them.",links:[{label:"Resources",href:"/resources"}]},
];
export async function POST(request:Request){const{question=""}=await request.json() as {question?:string};const q=question.toLowerCase();if(["my agenda","show my agenda","my reservations","what have i reserved"].some(term=>q.includes(term))){const user=await getEventUser();if(!user)return Response.json({answer:"Please use Participant Sign In to view your private agenda and reservations.",links:[{label:"Participant Sign In",href:"/signin"}]});try{const rows=await getDb().select().from(activityReservations).where(eq(activityReservations.userEmail,user.email));const ids=new Set(rows.filter(row=>row.status==="confirmed").map(row=>row.activityId));const activities=EVENT_ACTIVITIES.filter(item=>ids.has(item.id));return Response.json({answer:activities.length?`You currently have ${activities.length} reservation${activities.length===1?"":"s"}: ${activities.map(item=>`Day ${item.day} — ${item.title}`).join("; ")}. Open your hub for the full agenda.`:"You have no optional activity reservations yet. Your participant hub shows the draft official programme and available experiences.",links:[{label:"Open my hub",href:"/dashboard"}]})}catch{return Response.json({answer:"Your personal agenda is temporarily unavailable. Please open the participant hub and try again.",links:[{label:"Open my hub",href:"/dashboard"}]})}}const match=knowledge.find(item=>item.terms.some(term=>q.includes(term)));return Response.json(match||{answer:"That information has not yet been published by the organizers. I will not invent unconfirmed event details.",links:[{label:"Contact & concierge",href:"/contact"}]})}
