import { desc, eq } from "drizzle-orm";
import { getDb } from "@/db";
import { announcements, participantAccess, registrations } from "@/db/schema";
import { getEventUser } from "@/lib/event-auth";
import { isAdminEmail } from "@/lib/admin";
import { isParticipantEmailConfigured, sendParticipantEmail } from "@/lib/participant-emails";

async function admin() { const user = await getEventUser(); return user && isAdminEmail(user.email) ? user : null; }
export async function GET(){if(!await admin())return Response.json({error:"Organizer access required."},{status:403});const rows=await getDb().select().from(announcements).orderBy(desc(announcements.createdAt));return Response.json({announcements:rows,emailReady:isParticipantEmailConfigured()},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:Request){const user=await admin();if(!user)return Response.json({error:"Organizer access required."},{status:403});const body=await request.json() as {title?:string;body?:string;level?:string;emailParticipants?:boolean};if(!body.title?.trim()||!body.body?.trim())return Response.json({error:"Headline and update are required."},{status:400});const level=["update","important","deadline"].includes(body.level||"")?body.level!:"update";const[row]=await getDb().insert(announcements).values({title:body.title.trim(),body:body.body.trim(),level,createdBy:user.email}).returning();let delivery={requested:false,sent:0,failed:0,status:"not_requested"};if(body.emailParticipants){delivery={requested:true,sent:0,failed:0,status:isParticipantEmailConfigured()?"sending":"not_configured"};if(isParticipantEmailConfigured()){const[registrationRows,accessRows]=await Promise.all([getDb().select({email:registrations.email,userEmail:registrations.userEmail}).from(registrations),getDb().select().from(participantAccess)]);const blocked=new Set(accessRows.filter(item=>item.status!=="active").map(item=>item.userEmail));const recipients=[...new Set(registrationRows.map(item=>(item.userEmail||item.email).toLowerCase()).filter(email=>email&&!isAdminEmail(email)&&!blocked.has(email)))];for(const email of recipients){const result=await sendParticipantEmail({to:email,subject:`${level==="deadline"?"Deadline":"Event update"} · ${body.title.trim()}`,heading:body.title.trim(),body:body.body.trim(),actionLabel:"Open participant hub",actionUrl:`${new URL(request.url).origin}/dashboard`});if(result.status==="sent")delivery.sent+=1;else delivery.failed+=1}delivery.status=delivery.failed?"partial":"sent"}}return Response.json({announcement:row,delivery},{status:201})}
export async function PATCH(request:Request){if(!await admin())return Response.json({error:"Organizer access required."},{status:403});const body=await request.json() as {id?:number;title?:string;body?:string;level?:string;published?:boolean};if(!Number.isInteger(body.id))return Response.json({error:"Announcement required."},{status:400});const updates:{title?:string;body?:string;level?:string;published?:boolean}={};if(body.title!==undefined)updates.title=body.title.trim();if(body.body!==undefined)updates.body=body.body.trim();if(body.level!==undefined&&["update","important","deadline"].includes(body.level))updates.level=body.level;if(typeof body.published==="boolean")updates.published=body.published;const[row]=await getDb().update(announcements).set(updates).where(eq(announcements.id,body.id!)).returning();return row?Response.json({announcement:row}):Response.json({error:"Announcement not found."},{status:404})}
export async function DELETE(request:Request){if(!await admin())return Response.json({error:"Organizer access required."},{status:403});const{id}=await request.json() as {id?:number};if(!Number.isInteger(id))return Response.json({error:"Announcement required."},{status:400});await getDb().delete(announcements).where(eq(announcements.id,id!));return Response.json({deleted:true})}
