import { eq } from "drizzle-orm";
import { getEventUser } from "@/lib/event-auth";
import { getDb } from "@/db";
import { dailyRecaps,recapPhotos } from "@/db/schema";
import { isAdminEmail } from "@/lib/admin";
import { getRuntimeEnv } from "@/lib/runtime-env";

async function authorized(){const user=await getEventUser();return Boolean(user&&isAdminEmail(user.email))}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!await authorized())return Response.json({error:"Organizer access required."},{status:403});const{id}=await params;const recapId=Number(id);const body=await request.json() as {title?:string;summary?:string;eventDate?:string;status?:string};if(!Number.isInteger(recapId))return Response.json({error:"Invalid recap."},{status:400});const updates:{title?:string;summary?:string;eventDate?:string;status?:string;publishedAt?:string|null;updatedAt:string}={updatedAt:new Date().toISOString()};if(body.title!==undefined)updates.title=body.title.trim();if(body.summary!==undefined)updates.summary=body.summary.trim();if(body.eventDate!==undefined)updates.eventDate=body.eventDate;if(body.status!==undefined){if(!["draft","published"].includes(body.status))return Response.json({error:"Invalid status."},{status:400});if(body.status==="published"){const photos=await getDb().select({id:recapPhotos.id}).from(recapPhotos).where(eq(recapPhotos.recapId,recapId)).limit(1);if(!photos.length)return Response.json({error:"Upload at least one photo before publishing."},{status:400})}updates.status=body.status;updates.publishedAt=body.status==="published"?new Date().toISOString():null}const[recap]=await getDb().update(dailyRecaps).set(updates).where(eq(dailyRecaps.id,recapId)).returning();if(!recap)return Response.json({error:"Recap not found."},{status:404});return Response.json({recap})}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){if(!await authorized())return Response.json({error:"Organizer access required."},{status:403});const{id}=await params;const recapId=Number(id);const photos=await getDb().select({fileKey:recapPhotos.fileKey}).from(recapPhotos).where(eq(recapPhotos.recapId,recapId));if(photos.length)await getRuntimeEnv().BUCKET.delete(photos.map(photo=>photo.fileKey));await getDb().delete(dailyRecaps).where(eq(dailyRecaps.id,recapId));return Response.json({deleted:true})}
