import type{Metadata}from"next";
import Link from"next/link";
import{PageShell}from"@/components/PageShell";
export const metadata:Metadata={title:"Accommodations, travel and transportation"};
export default function TravelPage(){return <PageShell><main><section className="page-hero"><div className="page-hero-inner"><div className="breadcrumb"><span>Home</span><span>/</span><span>Register & Travel</span></div><p className="eyebrow">PLAN WITH CONFIRMED INFORMATION</p><h1>Your journey<br/>to Abidjan.</h1><p>This is the authoritative location for accommodation, venue, visa and transportation guidance. Do not make non-refundable arrangements from placeholder information.</p></div></section><section className="content-shell travel-directory">
  <article id="accommodations" className="travel-section anchor-section"><div className="travel-section-index">01</div><div><span className="status-label">Pending</span><p className="eyebrow">ACCOMMODATIONS</p><h2>Official hotel information.</h2><p>Partner hotels, room rates, booking links, deadlines and included services have not yet been confirmed. Approved accommodation information will be published only in this section.</p></div></article>
  <article id="transportation" className="travel-section anchor-section"><div className="travel-section-index">02</div><div><span className="status-label">Pending</span><p className="eyebrow">TRAVEL AND TRANSPORTATION</p><h2>Arriving and moving around Abidjan.</h2><p>Recommended arrival windows, airport-transfer options, local transportation and event shuttle arrangements remain to be announced.</p></div></article>
  <article id="venue" className="travel-section anchor-section"><div className="travel-section-index">03</div><div><span className="status-label">Venue to be announced</span><p className="eyebrow">VENUE INFORMATION</p><h2>Abidjan hosts the symposium.</h2><p>The city is confirmed. The venue name, address, map, accessibility information and arrival instructions are awaiting organizer approval.</p></div><div className="destination-image" role="img" aria-label="Abidjan and West African transform margin visual"/></article>
  <article id="visa" className="travel-section anchor-section"><div className="travel-section-index">04</div><div><span className="status-label">Pending verification</span><p className="eyebrow">VISA INFORMATION</p><h2>Guidance by nationality.</h2><p>Visa requirements vary by traveler. Verified guidance and invitation-letter procedures will be published after organizer review.</p><Link className="feature-link" href="/contact">Contact the event team →</Link></div></article>
  </section></main></PageShell>}
